version: '3.7'
services:
  mysql:
    image: mysql:9
    container_name: mysql
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rocketseat-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    networks:
      - apirocket-network

  api-rocket:
    build:
      context: .
    container_name: api-rocket
    ports:
      - 3001:3000
    depends_on:
      - mysql
    networks:
      - apirocket-network

volumes:
  mysql-volume:

networks:
  apirocket-network:
    driver: bridge
