name: CI

# Evento que vai disparar o workflow (push, pull_request, etc) chamado de "trigger"
on:
  push: # Evento push - Quando um push é feito e em qual branch
    branches:
      - main # Branch main

# 1 Workflow pode ter vários jobs e um job pode ter várias steps
jobs:
  build:
    name: "Build and Push" # Nome do job
    runs-on: ubuntu-latest # Sistema operacional que o job vai rodar

    steps:
      - name: Checkout Repository # Nome da step
        uses: actions/checkout@v4 # Ação que faz o checkout do repositório

      - name: Setup Node.js # Nome da step
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install # Comando que vai rodar na step
      - run: npm run test

      - name: Generate tag for image
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build docker image 
        run: |
          docker build -t restapi-rocketseat:${{ steps.generate_tag.outputs.sha }} .