name: CI

# Evento que vai disparar o workflow (push, pull_request, etc) chamado de "trigger"
on:
  push: # Evento push - Quando um push é feito e em qual branch
    branches:
      - main # Branch main

# 1 Workflow pode ter vários jobs e um job pode ter várias steps
jobs:
  build:
    name: "Build and Push" # Nome do job
    runs-on: ubuntu-latest # Sistema operacional que o job vai rodar

    steps:
      - name: Checkout Repository # Nome da step
        uses: actions/checkout@v4 # Ação que faz o checkout do repositório

      - name: Setup Node.js # Nome da step
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install # Comando que vai rodar na step
      - run: npm run test

      - name: Generate tag for image
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT
      
      - name: Configure AWS Credentials 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ vars.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ vars.AWS_SESSION_TOKEN }}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ vars.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push docker image 
        id: build-docker-image
        env: 
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          TAG: ${{ steps.generate_tag.outputs.sha }}
        run: |
          docker build -t $ECR_REGISTRY/rocketseat-nestjs-api:$TAG .
          docker push $ECR_REGISTRY/rocketseat-nestjs-api:$TAG
          IMAGE=$(echo $ECR_REGISTRY/rocketseat-nestjs-api:$TAG)
          echo "image=$IMAGE" >> $GITHUB_ENV

      # - name: Build and Push docker image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     push: true
      #     tags: bandeirapk/nestapi-nodejs:${{ steps.generate_tag.outputs.sha }}, bandeirapk/nestapi-nodejs:latest
      
      - name: Deploy to App Runner
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          name: rocketseat-nestjs-api
          image: ${{ steps.build-docker-image.outputs.image }}
          region: us-east-1
          cpu: 1
          memory: 2
          port: 3000